### ISSUE TITLE
Can't estimate a new ticket after a couple of estimations

### ISSUE THREAD

**Issue by manuellazzari-cargoone** [fpischedda/unrefined#26]
For some reason, it appears that the system breaks when trying to create the pages for a ticket after a couple of other tickets have been worked on.

Sequence of actions (not sure if it can be reproduced this way):

1. created links for ticket A
2. accessed results page for ticket A
3. created links for ticket B
4. accessed results page for ticket B
5. trying to create links for ticket C
5a. if doing it from the results page for ticket B, nothing happens when clicking on "Start!"
5b. if doing it from https://unrefined.one, nothing happens when clicking on "Start!"

Tried also to do that in an extra incognito window.

Browser Chrome

EDIT: it seems that the problem may be related to the fact that maybe the ticket is already been estimated according to the system?

**Comment by fpischedda** [comment]
Looking at logs it looks like that the refinement session data has been removed resulting in internal errors.
This is because the application state is currently store in RAM only (it is an alpha anyway :wink: ) and there is a process to cleanup old refinements (now it removes refinements older than 12 hours); also, on application restarts the state is obviously lost.

There is an ongoing effort to setup some kind of persistent storage but, for now, we have to live with this limitation :smile:

**Comment by fpischedda** [comment]
Solved some time ago :wink:
